Update precode.go
dbulatov23/go-rest-api-homework pull request #1
Opened 2024-04-08 22:31 UTC by dbulatov23

2024-04-09 10:14 UTC, just-musha requested changes
Привет! Код работает корректно, но в ПР отображаются не все изменения, и поэтому я не могу прокомментировать сам код. Можешь пожалуйста пересоздать ПР, чтобы в нем были видны все твои изменеия?

Как вариант что можно сделать - убрать коммит с твоими изменениями из ветки main
```
git checkout main
git reset --hard HEAD~
git push -f origin main
```

2024-04-11 16:31 UTC, dbulatov23 commented
Вроде получилось)

2024-04-11 19:31 UTC, just-musha requested changes
Привет! В целом все окей, предлагаю поправить возврат ошибок - использовать метод http.Error и возвращать не только статус код, но и сообщение. Остальное не критично. Присылай правки.

2024-04-11 19:31 UTC, just-musha commented on precode.go
> +		w.WriteHeader(http.StatusBadRequest)
Здесь лучше использовать метод `http.Error` https://pkg.go.dev/net/http#Error

2024-04-11 19:31 UTC, just-musha commented on precode.go
> +		w.WriteHeader(http.StatusBadRequest)
И здесь, и везде где нужно вернуть ошибку пользователю

2024-04-11 19:31 UTC, just-musha commented on precode.go
> +		http.Error(w, "Задача не найдена", http.StatusNoContent)
Здесь лучше BadRequest вернуть, у NoContent другое назначение https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204

2024-04-11 19:31 UTC, just-musha commented on precode.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Тут InternalServerError скорее, тк ошибка внутренняя

2024-04-11 19:31 UTC, just-musha commented on precode.go
> +	tasks[task.ID] = task
А если таска с таким ID уже существует?
Тогда она не добавится, а перезатрется существующая
Лучше добавить проверку и если уже есть - вернуть BadRequest

2024-04-12 13:51 UTC, dbulatov23 commented on precode.go
> +	tasks[task.ID] = task
я сделал проверку, но как будто она не работает... и не могу понять почему

2024-04-13 13:11 UTC, just-musha requested changes
Круто что добавляешь проверку в методе postTask - давай её добьем! Оставила 2 комента.

2024-04-13 13:11 UTC, just-musha commented on precode.go
> +	if !ok {
А условие не наоборот? Если задача найдена - тогда возвращаем ошибку, нет?

2024-04-13 13:11 UTC, just-musha commented on precode.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
А что за err здесь? Лучше здесь свою строку задать, например ''задача с таким id уже сущестует'

2024-04-13 13:11 UTC, just-musha commented on precode.go
> +		w.WriteHeader(http.StatusOK)
А здесь почему поменял? Все было правильно. Не нашлась задача - не смогли удалить, тк ползователь передал не существующий id.

2024-04-14 16:28 UTC, merged

2024-04-14 16:34 UTC, dbulatov23 commented
я случайно вмержил этот PR в ветку main с изменениями последними...  
вот тут есть мой последний коммит с правками по вашим последним замечаниям  - https://github.com/Yandex-Practicum/go-rest-api-homework/commit/d8976effe932cfe92a7fece6038377ce0b48a25b

2024-04-14 19:53 UTC, just-musha commented
Отлично! Теперь все ок! Принято!